apiVersion: v1
kind: Service
metadata:
  name: bank-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: bank-app
  ports:
    - protocol: TCP
      port: 10208
      targetPort: 10208
      nodePort: 31234  
