apiVersion: v1
kind: Service
metadata:
  name: bank-app-service
  namespace: default
spec:
  selector:
    app: bank-app
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8082
  type: NodePort   
